name: Zombies
version: 0.1.0
main: com.mango.zombies.Main
description: Zombies plugin to replicate the Call of Duty Zombies experience
author: Useless_Mango

commands:
    info:
        description: Get plugin information
        usage: /<command>
        
    createmap:
        description: Creates a new map
        usage: /<command> [ID] [name]
        
    createweaponclass:
       description: Creates a new weapon class
       usage: /<command> [name] [weapon type] [can Pack-A-Punch? true/false]
        
    createweapon:
        description: Creates a new weapon
        usage: /<command> [ID] [name] [weapon class]
        
    getweapon:
        description: Puts the specified weapon in your inventory
        usage: /<command> [weapon ID]