name: Zombies
version: 0.1.0
main: com.mango.zombies.Main
description: Zombies plugin to replicate the Call of Duty Zombies experience
author: Useless_Mango

commands:
    info:
        description: Get plugin information
        usage: /<command>
        
    createmap:
        description: Creates a new Zombies map
        usage: /<command> [map name]
        
    createweapon:
        description: Creates a new weapon for use in gameplay
        usage: /<command> [weapon name]
        
    getweapon:
        description: Puts the specified weapon in your inventory
        usage: /<command> [weapon name]