name: Zombies
version: 1.0.0
main: com.mango.zombies.Main
description: Zombies plugin to replicate the Call of Duty Zombies experience
author: Useless_Mango

commands:
    z_createmap:
        description: Creates a new map
        usage: /<command> <map name>
        
    z_listmaps:
        description: Lists all available maps
        usage: /<command>
        
    z_enablemap:
        description: Enables a map if it is disabled
        usage: /<command> <map name>
        
    z_disablemap:
        description: Disables a map if it is enabled
        usage: /<command> <map name>
        
    z_mapinfo:
        description: Shows the information of map
        usage: /<command> <map name>
        
    z_editmap_title:
        description: Sets the title for a map
        usage: /<command> <map name> <new map name>    
        
    z_editmap_description:
        description: Sets the description for a map
        usage: /<command> <map name> <description>
        
    z_deletemap:
        description: Deletes a map
        usage: /<command> <map name>